
#set page(paper: "a4", margin: 2cm)
#set text(font: "Linux Libertine", size: 12pt)

#align(center)[
  #text(size: 24pt, weight: "bold")[SDG Impact Report]
  
  #v(1em)
  #text(size: 16pt)[Project: Smart Water Purification with IoT]
  
  #text(size: 14pt)[By: Test Student]
]

#v(2em)

== Project Summary
This student project details a smart water purification system utilizing IoT sensors to monitor water quality in real time. This directly supports SDG 6 (Clean Water and Sanitation) by ensuring access to safe and clean drinking water, and utilizes technology and innovation aligning with SDG 9 (Industry, Innovation, and Infrastructure).

#v(2em)

== Impact Footprint
#align(center)[
  #image("../radar_maps/radar_f51cdb0c.png", width: 80%)
]

#v(1fr)
_Report generated by Automated Assessment System_
