
#set page(paper: "a4", margin: 2cm)
#set text(font: "Linux Libertine", size: 12pt)

#align(center)[
  #text(size: 24pt, weight: "bold")[SDG Impact Report]
  
  #v(1em)
  #text(size: 16pt)[Project: Demo: AI for Ocean Cleaning]
  
  #text(size: 14pt)[By: Jane Doe (Demo)]
]

#v(2em)

== Project Summary
This innovative project leverages advanced AI and autonomous drone technology to actively mitigate marine pollution by collecting and classifying plastic waste in the ocean. By targeting plastic debris, the initiative directly supports the preservation of marine ecosystems and helps protect diverse aquatic life from the hazards of ingestion and entanglement. Additionally, the data gathered from classifying the waste can provide crucial insights for tracking pollution sources and optimizing waste management strategies. Ultimately, this technological solution contributes significantly to global efforts in safeguarding our oceans and ensuring long-term ecological balance.

#v(2em)

== SDG Radar Map
#align(center)[
  #image("D:/ABHINAV/projects/SDG PROJECT/public/radar_maps/radar_92e3027e.png", width: 80%)
]

#v(2em)
#align(center)[
  #text(style: "italic")[Report automatically generated by AI.]
]
