
#set page(paper: "a4", margin: 2cm)
#set text(font: "Linux Libertine", size: 12pt)

#align(center)[
  #text(size: 24pt, weight: "bold")[SDG Impact Report]
  
  #v(1em)
  #text(size: 16pt)[Project: Smart Water Purification with IoT]
  
  #text(size: 14pt)[By: Test Student]
]

#v(2em)

== Project Summary
This project implements an IoT-based smart water filtration and real-time quality monitoring system, which directly supports the targets of SDG 6 (Clean Water and Sanitation) by improving water quality and access to safe drinking water through technological innovation.

#v(2em)

== Impact Footprint
#align(center)[
  #image("../radar_maps/radar_97817483.png", width: 80%)
]

#v(1fr)
_Report generated by Automated Assessment System_
